# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d1d75bf1145076d0705378422d55159c03fde25d36e57bf2d7639ee6d28bc78a08c4fdd21623905d6208e7d5bea174ab98e0ddb4b96113d7497c80c143cbe3

test:
  secret_key_base: 4461ed851c1ebffd3d30e254d1537487fc26661aec07be98e4f5bea72c1049058e704ed151d4288313b69ad266b59242be45c8899e29f84008e630fc8f132b9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
